name: My first workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"
          echo "$(uname -a)"

      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: List files in the repo
        run: |
          echo "The repository ${{ github.repository }} contains the files:"
          tree
